### ISSUE TITLE
Can you make a licence please ?

### ISSUE THREAD

**Issue by dcorralf** [jeetendra-choudhary/PersonalBlog#1]
Hi Jeetendra,

Hope your are well, I've interested in your code about Cognito, I'm a Computer Science student from Spain and I will work with your code for a project in my university. Can you have a licence please ? for example a MIT licence it will be great, or Apache one of your particular interest. Thanks a lot !!

Have a nice day ahead.

**Comment by jeetendra-choudhary** [comment]
Hello David,

Included the license. Hope it works for you. Would appreciate if you can contribute to main repo too.

Warm Regards
Jeet

**Comment by dcorralf** [comment]
Ok Jeetendra, I will check the code and make some tests for the university work, if I've some proposition, I will contact you again. Thanks a lot !!

Have a nice day ahead.
